### PR TITLE
Adjust live ISO build rules for bookworm

### PR DESCRIPTION
**Pull request by petterreinholdtsen**

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
I recommend to put these into a new branch bookworm, and not merge it into the buster branch, but github did not provide that option so it look like it should be merged into the buster branch.

**Comment by petterreinholdtsen** [comment]
Note, building for bookworm require a newer live-build package than the one available in Debian/Buster until https://bugs.debian.org/1016098 is fixed.

I recommend the fixes for Buster in #5 go into buster first and then rebase this pull request on top of that new buster branch to make it easier to track in git the changes relevant for bookworm.

**Comment by silopolis** [comment]
Meaning? You can't push to a non existing remote branch?

**Comment by silopolis** [comment]
> Note, building for bookworm require a newer live-build package than the one available in Debian/Buster

Can we build on Sarge?
Seriously guys, can't believe the amount of time and energy spent on OLD stable related pseudo issues we create ourself, like if we hadn't enough to do!

Let's support STABLE to build TESTING images and... BASTA !!!
For our sanity and projects survival sake, let's look FORWARD please 🙏🙏🙏

**Comment by petterreinholdtsen** [comment]
[Jérémie Tarot]
> Meaning? You can't push to a non existing remote branch?

Someone need to create a bookworm branch in the
LinuxCNC/linuxcnc-live-build repository, and then this change can be
merged into this branch.

> Can we build on Sarge?

Nope, but I do expect building on Bullseye will be trivial. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by andypugh** [comment]
There has been a bookworm branch in linuxcnc-live-build since mid August: https://github.com/LinuxCNC/linuxcnc-live-build/commits/bookworm

**Pull request merged**
