### PR TITLE
Bookworm 2.9.1 - install from linuxcnc-repositories

### PR DESCRIPTION
**Pull request by rodw-au**

### CODE REVIEW

**Comment by andypugh** [comment]
I think that this one looks like a merge? It contains way more commits than I think it should.

**Comment by ighvh** [comment]
This PR should probably go into the **bookworm** branch and not **buster**.

**Comment by rodw-au** [comment]
I'm a bit lost here. I closed this PR but #31 has been correctly merged from what I can see.

**Comment by andypugh** [comment]
Yes, #31 looked OK?

**Pull request closed without merging**
